### ISSUE TITLE
Support for authentication and TLS

### ISSUE THREAD

**Issue by dannyclark** [cole/aiosmtplib#1]
I'd like to use this with email services (e.g. mandrill, sendgrid, Amazon SES) and as a pre-requisite it would need to support authentication.

Ideally it should support TLS for security, which may be a pre-requisite of some email services.

**Comment by cole** [comment]
Unfortunately STARTTLS implementation is a bit tricky, as asyncio doesn't support it currently:
https://code.google.com/p/tulip/issues/detail?id=79
https://groups.google.com/forum/#!msg/python-tulip/kEYYkq-TNnw/ueouVU3CvOMJ

If I find a workaround, obviously I'll implement it.

**Comment by imbolc** [comment]
Still nothing changed?

**Comment by dannyclark** [comment]
After reading the above response & thinking about it a bit more, I decided to use the APIs of the 3rd party services directly (via the aiohttp HTTP client) i.e. that functionality doesn't necessarily need to be built into this library.

YMMV but that worked for me.

**Comment by cole** [comment]
I *think* STARTTLS is no longer so much of a problem in 3.5, I just haven't got around to implementing it yet. I'll update this ticket when I get there.

**Comment by thijstriemstra** [comment]
+1 (note to self: always check the tickets before implementing a new library..)

**Comment by kozzztik** [comment]
I have working implementation of STARTTLS. Its a little bit tricky, but not too much. Its already tested in production enviroment, I just need a few days to find time to merge it back and make pull request.

**Comment by cole** [comment]
So my implementation of STARTTLS is working now in my testing (no unit tests yet), but it's a bit hacky unfortunately. Please try it out and let me know if you find any bugs. I haven't yet packaged the new version on pip.

auth, SSL connections, and STARTTLS should all be supported now.

@kozzztik if you have any improvements, it would be awesome if you could package them into a pull request. Or point me at some example code.

@thijstriemstra should have had a note in the README, sorry.

**Comment by thijstriemstra** [comment]
@cole tested lastest master just now it's starting to work, great!

- server.connect() just hangs if the server is not available/non-existing. Is there a timeout that can be specified?

My code:

```python
logger.debug('Connecting to SMTP server...')

server = aiosmtplib.SMTP(host, port, loop=self.loop)
self.loop.run_until_complete(server.connect())
#server.set_debuglevel(enable_log)

if tls is True:
    logger.debug('Starting TLS...')
    server.ehlo()
    server.starttls()
    server.ehlo()

if user != '':
    if password is None:
        logger.warning('Missing valid SMTP password')
    else:
        logger.info('SMTP user: {}'.format(user))
        server.login(user, password)

# send email async
msg_str = msg.as_string()
async def send_a_message():
    await server.sendmail(sender, receivers.split(COMMASPACE),
        msg_str)

self.loop.run_until_complete(send_a_message())
```

**Comment by cole** [comment]
@thijstriemstra  yeah that's next on the list, should be pretty quick though. I've made a ticket for it, #8. Closing this issue as auth and STARTTLS are now implemented and working.
