### ISSUE TITLE
why not split message to from, subject and body vars?

### ISSUE THREAD

**Issue by wsbmilk** [cole/aiosmtplib#11]
rt

**Comment by kozzztik** [comment]
subject is email header and it have no direct relation with SMTP protocol?

**Comment by cole** [comment]
The idea behind the API is that the `sendmail` method allows you to send a raw message, and the `send_message` method allows you to send a constructed `EmailMessage` object that lets you specify the headers (e.g. subject) more conveniently. I think you're asking for changes to the `sendmail` method, is that correct? Is there a reason `send_message` doesn't work for you?

**Comment by wsbmilk** [comment]
thanks, i got it
