### ISSUE TITLE
How can i port from existing smtp

### ISSUE THREAD

**Issue by dduraipandian** [cole/aiosmtplib#116]
This is not the issue. I have email script in traditional smtp. How I can port to aiosmtplib? Is there any steps can you please help me with that?

https://github.com/cole/aiosmtplib/issues/112

If I try something similar to the issue: 112, will it work?

Thanks..

**Comment by cole** [comment]
Hi, sorry for the slow response. There's no direct porting instructions; I think most of what needs to be covered there is the difference between async and sync code, and that's a big topic.


If you're wondering how to use the lib in general, check out the samples in the documentation: https://aiosmtplib.readthedocs.io/en/latest/usage.html#multipart-messages
