### ISSUE TITLE
Not recognizing auth types for exchange server

### ISSUE THREAD

**Issue by ChristianHopper** [cole/aiosmtplib#119]
I am unable to send emails from a Microsoft Exchange account hosted on Office365. My credentials are valid and I have succesfully tested sending emails with smtplib. For some reason `SMTPAuth.server_auth_methods` ends up being an empty list and then sending an email fails with 

> SMTP AUTH extension not supported by server.

You can see a minimal working example below (I have not tried to reproduce the error without an Office 365 account).

```
import asyncio
from email.message import EmailMessage

import aiosmtplib

PASSWORD = 'password'
USER = 'user@mydomain.com'

async def send_hello_world():
    message = EmailMessage()
    message["From"] = 'user@mydomain.com'
    message["To"] = "somebody@example.com"
    message["Subject"] = "Hello World!"
    message.set_content("Sent via aiosmtplib")

    send = await aiosmtplib.send(message,
                          hostname="smtp.office365.com",
                          port=587,
                          password=PASSWORD,
                          username=USER)
    return send

event_loop = asyncio.get_event_loop()
event_loop.run_until_complete(send_hello_world())
```

**Comment by cole** [comment]
You need to set `start_tls=True` when using port 587. I'll change the exception so that it gives a hint.

**Comment by ChristianHopper** [comment]
You're right - it works perfectly now! Thanks!
