### ISSUE TITLE
SMTP AUTH extension not supported by server

### ISSUE THREAD

**Issue by coodblooded** [cole/aiosmtplib#122]
async def send_hello_world():
    message = EmailMessage()
    client = SMTP(hostname="smtp.gmail.com", port=587,username='xyz@gmail.com',password='************', use_tls=False)
    print("sandeep patel")
    message["From"] = "xyz@gmail.com"
    message["To"] = "pqr@gmail.com"
    message["Subject"] = "Hello World!"
    message.set_content("Sent via aiosmtplib")
    async with client:
        await client.smtp_client(message)

Getting Error
        '    raise SMTPException("SMTP AUTH extension not supported by server.")\n'
        'aiosmtplib.errors.SMTPException: SMTP AUTH extension not supported by server.\n'

**Comment by cole** [comment]
This just came up as #119. You need to set start_tls=True when using port 587.

I've been meaning to add a hint to the exception, please leave this issue open to remind me to do that 🙂

**Comment by cole** [comment]
Hint added now.
