### ISSUE TITLE
login needs elho every time

### ISSUE THREAD

**Issue by DeoLeung** [cole/aiosmtplib#13]
Hi,

thanks for the great lib, now I use it couple with tornado to send email async.

there is a problem with the check here
https://github.com/cole/aiosmtplib/blob/master/aiosmtplib/smtp.py#L464
it does nothing

I still need to do ehlo() every time to make it work, otherwise I will get 503
```python
async with smtp:
  await smtp.ehlo()
  await smtp.login(...)
  ...
  await smtp.send_message()
```
I'm not very familiar with smtp protocol, also I wonder whether there's a plan to simplify the process to be like
```python
smtp = SMTP(host, port, user, pwd)
async with smtp:
  ...
  await smtp.send_message(...)
```
so I don't need to worry about the login each time

**Comment by cole** [comment]
Thanks for reporting, should be fixed now in master. There was an error where it was saving the EHLO response after disconnect.

**Comment by cole** [comment]
As to adding the login details to init, I don't see why we couldn't have them as keyword arguments. I'll add that to my list.
