### ISSUE TITLE
smtp context shall check the connect status

### ISSUE THREAD

**Issue by DeoLeung** [cole/aiosmtplib#14]
https://github.com/cole/aiosmtplib/blob/master/aiosmtplib/smtp.py#L56

I think the return response code shall be checked, if it's not 220(or store it in attribute so it can be checked later)

**Comment by cole** [comment]
It is checked, here: https://github.com/cole/aiosmtplib/blob/master/aiosmtplib/connection.py#L62

If the response is not 220 SMTPConnectError is raised.

Are you finding cases where that's not working?

**Comment by DeoLeung** [comment]
argh, good, checked that it's working
in the previous versions I did
```python
code, _ = await smtp.connect()
```
instead of 
```python
with SMTP(...):
  ...
```
 so I thought I shall check it.
