### ISSUE TITLE
When connecting to port 25 or 587 and using TLS, SMTP.connect() has to be plain text before issuing starttls.

### ISSUE THREAD

**Issue by nihlaeth** [cole/aiosmtplib#16]
When connecting to port 25 or 587 and using TLS, SMTP.connect() has to initiate a plaintext connection before issuing starttls.

```
Traceback (most recent call last):
  File "/git/dnd/lib64/python3.6/site-packages/aiosmtplib/connection.py", line 46, in create_connection
    connect_future, timeout=timeout, loop=loop)
  File "/usr/lib64/python3.6/asyncio/tasks.py", line 352, in wait_for
    return fut.result()
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 802, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 828, in _create_connection_transport
    yield from waiter
  File "/usr/lib64/python3.6/asyncio/sslproto.py", line 503, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib64/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:749)
```

```python
async with aiosmtplib.SMTP(
        loop=cfg.APP.loop,
        hostname=cfg.SMTP_HOST,
        port=cfg.SMTP_PORT,
        use_tls=cfg.SMTP_TLS,
        ) as smtp:
    if cfg.SMTP_TLS:
        await smtp.starttls(validate_certs=False)
    if cfg.SMTP_USERNAME:
        await smtp.login(cfg.SMTP_USERNAME, cfg.SMTP_PASSWORD)
    msg = MIMEText(body, 'html')
    msg['Subject'] = subject
    msg['From'] = cfg.SMTP_SENDER
    msg['To'] = recipient
    await smtp.send_message(msg)
```
To be clear, cfg.SMTP_PORT was set to 587, and cfg.SMTP_TLS to True in this case.

**Comment by cole** [comment]
If you're using STARTTLS, then the initial connection is unencrypted, so you should pass `use_tls=False` to the SMTP init function. This is a bit confusing, but I'm not sure how to make it clearer as it reflects the general confusion around purely TLS connections vs STARTTLS.

**Comment by nihlaeth** [comment]
Isn't it a matter of SSL versus TLS? From what I understand SMTP servers using SSL  accept encrypted connections, and the ones using TLS use a plaintext with the STARTTLS method. If that is the case,  I would propose renaming the `use_tls` argument to `use_ssl`. But I'm by no means an expert on this, that's why I opened this issue instead of submitting a pull request.

I found that workaround on my own,  but it took reading a lot of source code before I came to it. Maybe it's worth writing an example, or otherwise making note of this particular problem in the readme?

**Comment by cole** [comment]
SSL and TLS are usually used interchangeably, as TLS is newer replacement for SSL, basically a new version. TLS is frequently referred to as SSL (including in the Python standard library), but all versions of SSL now have known vulnerabilities, so the future will hopefully by TLS only - that's why I went with use_tls for the argument name.

Servers supporting SSL/TLS can do so via an encrypted connection (SSL/TLS handshake on connect) or a plaintext connection followed by STARTTLS. The resulting encryption is the same.

This is a common gotcha and could definitely use better docs and a prominent example. Thanks for bringing it up, I'll add that to the list.

**Comment by cole** [comment]
Added to the README for now.
