### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by HarrySky** [cole/aiosmtplib#161]
Hi, thanks for the great library! :tada: 
Could you please release a new version to PyPI? I am experiencing problem with `mypy` static type checking, and I see `py.typed` file was included on May 4th, but last release date was March 2nd.

**Comment by cole** [comment]
Right, of course. 1.1.4 uploaded to pypi.

**Comment by cole** [comment]
Er...was still tagged as dev. Should now be available as 1.1.4 stable.

**Comment by HarrySky** [comment]
I used dev version, thought that you don't consider this a stable release 😁
