### ISSUE TITLE
TypeError: connect() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by EmilIsLookingForThis** [cole/aiosmtplib#162]
First of all thank you for offering this project to us :)

I am working on an program to verify email addresses of people who bought in our shop or subscribed to our newsletter. Started it with a sync process but was really slow. Thats why I built it up async with multiple threads and found this project.

I want to connect to the email server of a given domain via mx. With smtplib everything works fine, here with aiosmtplib it shows me this error message, tried various things to solve it but nothing works.

This snipped is part of a function that is called by an async one with the multiple threads:

>     try:
        records = dns.resolver.resolve(provider, 'MX')
        successful = True
    except (dns.resolver.NXDOMAIN, dns.resolver.NoAnswer):
        print('Disconnected at dns.resolver')
        successful = False

    if successful:

        # Get MX record for the domain
        mx_record = records[0].exchange
        mx = str(mx_record)

        # Get local server hostname
        local_host = socket.gethostname()

        # Connect to SMTP

        smtp_server = aiosmtplib.SMTP()

        smtp_server.connect(mx)

at this point it always shows me the error message "TypeError: connect() takes 1 positional argument but 2 were given" even though the mx record should just be one string.

Please have a look at it, Thanks a lot!

**Comment by cole** [comment]
It's a keyword argument, so I think you're looking for `smtp_server.connect(hostname=mx)`

**Comment by EmilIsLookingForThis** [comment]
Hi cole, 
Thanks a lot for your fast reply!
It worked in this way and i was able to get to the next step. Have more issues there. Will continue to do research on my own (am not that experienced and want to ensure that im not doing beginner mistakes before i ask here) and in case i don't get a solution ill get in touch with you.
Have a nice week and thanks again!
Best regards

**Comment by cole** [comment]
I'm going to close this, feel free to open new issues if needed.
