### ISSUE TITLE
does it support cc and bcc?

### ISSUE THREAD

**Issue by lixxu** [cole/aiosmtplib#17]
Not sure if it supports `cc` and `bcc` as I check the code and not found these options.

**Comment by cole** [comment]
CC & BCC are supported, in the same way as smtplib - add the addresses to the recipients, then include them on the CC or BCC header. Calling `send_message` on an `email.message.Message` object is an easy way to do this.

**Comment by lixxu** [comment]
seems not straight way like as `emails`, `marrow.mailer`, but thanks.
