### ISSUE TITLE
Enabling UTF-8 for Authetication

### ISSUE THREAD

**Issue by sabuhish** [cole/aiosmtplib#170]
Hi,

We are currently facing trouble with authentication. As passwords and usernames encoded into Ascii, some symbols cannot.
Will we have the support of UTF-8?

https://github.com/sabuhish/fastapi-mail/issues/55

Thanks a lot!

**Comment by cole** [comment]
Also an issue in stmplib: https://bugs.python.org/issue29750

This isn't really a straightforward solution unfortunately — assuming that UTF-8 is used is probably correct most of the time, but that behaviour isn't specified in any RFC as far as I can tell. Some SMTP servers support AUTH without supporting SMTPUTF8, also.

The most obvious solution to me right now is to allow the user to use bytes for username and passwords, and just passing that through if so.

**Comment by cole** [comment]
Ok, looking into it a bit more, I don't think we will cause any issues by switching the default from ASCII to UTF-8, and that should make it just work with Unicode strings for most people. I've also added the option to use bytes.

Please try the current main branch if you're able, and let me know if it works for you.

**Comment by sabuhish** [comment]
Thank you for the detailed information. Thanks for having the support of  UTF-8 you did a great job. 

As dependecy_link is deprecated in pip I am not able to pull over. [StackOverflow-Question](https://stackoverflow.com/questions/46320277/why-is-dependency-links-in-setup-py-deprecated). I also tried yesterday and today PEP 508 URL dependencies twine throws an error while uploading to PyPI.

Is there any possibility to release a new version so, the module can install dependencies from there?
Thanks in advance!

**Comment by cole** [comment]
@sabuhish you can try the 1.1.5 pre release: https://pypi.org/project/aiosmtplib/1.1.5.dev0/

**Comment by cole** [comment]
1.1.5 is out now with this change.
