### ISSUE TITLE
add github issues url to bug reporting docs section

### ISSUE THREAD

**Issue by sivanbecker** [cole/aiosmtplib#173]
when viewing docs on [readthedocs](https://aiosmtplib.readthedocs.io) ,on the [bug reporting part](https://aiosmtplib.readthedocs.io/en/latest/overview.html#bug-reporting) it says any bugs should be reported under Github issues. a hyperlink would simplify navigation :)

**Comment by cole** [comment]
Fixed via #174, thank you!
