### ISSUE TITLE
Pytest Assistance

### ISSUE THREAD

**Issue by trp07** [cole/aiosmtplib#179]
Good evening,

I know **issues** might not be the best place to ask this, but I can't seem to find anything online.  Any assistance is greatly appreciated! 

How might someone write a unit test in PyTest to test a function that calls `aiosmtplib.send()` inside it?  

For example:
```python 3
# Function in my application
async def myfunc():
    call_some_other_func()
    await aiosmtplib.send(...)

# Unit testing with PyTest
@pytest.mark.asyncio
async def test_myfunc():
    # what goes here?
```

**Comment by trp07** [comment]
I got everything I needed from this tutorial:
https://agariinc.medium.com/strategies-for-testing-async-code-in-python-c52163f2deab

**AsyncMock** is native to python 3.8, but the tutorial shows how to create one for earlier python versions. 

Apologies for opening an issue on the topic. I’ll close it with this comment :)

**Comment by cole** [comment]
Going to reopen as a reminder to add a testing section to the docs 🙂
