### ISSUE TITLE
Timed out waiting for server ready message

### ISSUE THREAD

**Issue by wayneking517** [cole/aiosmtplib#180]
I am hoping that it is appropriate to ask this question here. 

I am using:
```
async def send_txt(
    num: Union[str, int], carrier: str, email: str, pword: str, msg: str, subj: str
) -> Tuple[dict, str]:
    to_email = CARRIER_MAP[carrier]

    # build message
    message = EmailMessage()
    message["From"] = email
    message["To"] = f"{num}@{to_email}"
    message["Subject"] = subj
    message.set_content(msg)

    # send
    res = await aiosmtplib.send(message, username=email, password=pword, hostname=HOST, port=465, start_tls=True)
    msg = "failed" if not re.search(r"\sOK\s", res[1]) else "succeeded"
```

I get "aiosmtplib.errors.SMTPConnectTimeoutError: Timed out waiting for server ready message"

This code works when sending it to a gmail account but not to my ISP.

Any suggestions as to how to take this up with the ISP would be appreciated.

Thanks for the great code.

**Comment by cole** [comment]
Hmm, it might be `use_tls` vs `start_tls` which is kind of confusing. Port 465 is usually a `use_tls` connection (initially encrypted), 587 would be `start_tls` (upgraded after connect).

**Comment by wayneking517** [comment]
I resolved the issue. I am sorry for taking your time.. Thank you for responding.

**Comment by cole** [comment]
no worries!

**Comment by ggree1** [comment]
> I resolved the issue. I am sorry for taking your time.. Thank you for responding.

Sorry for asking after it's all over, What was the problem? Because I have also same issue with my smtp ISP.
