### ISSUE TITLE
Error trying to use the mail_options or rcpt_options arguments

### ISSUE THREAD

**Issue by eugro** [cole/aiosmtplib#181]
Trying to use the **mail_options** or **rcpt_options** arguments with **aiosmtplib.send** will result in error. This can be better illustrated with an example:

`import asyncio, aiosmtplib

async def test():
    msg = """Subject: Test

testing 1 2 3
"""
    await aiosmtplib.send(msg,
        sender='john@mail.com', recipients=['doe@orange.com'],
        mail_options=[], rcpt_options=[],
        hostname='127.0.0.1', port=8025,
        username=None, password=None, 
        start_tls=False, timeout=5)

event_loop = asyncio.get_event_loop()
event_loop.run_until_complete(test())`

The resulting error is:

`Traceback (most recent call last):
  File "~/send.py", line 16, in <module>
    event_loop.run_until_complete(test())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "~/send.py", line 8, in test
    await aiosmtplib.send(msg,
  File "/usr/lib/python3.9/site-packages/aiosmtplib/api.py", line 394, in send
    client = SMTP(**kwargs)
  File "/usr/lib/python3.9/site-packages/aiosmtplib/smtp.py", line 50, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/aiosmtplib/esmtp.py", line 37, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'mail_options'`

Thank you

**Comment by cole** [comment]
Thanks for reporting! This issue should be fixed in the 2.0 pre-release, [now on PyPI](https://pypi.org/project/aiosmtplib/2.0.0b0/). Would you mind testing it out?
