### ISSUE TITLE
aiosmtplib is not working. [SSL: WRONG_VERSION_NUMBER] wrong version number 

### ISSUE THREAD

**Issue by ystekno** [cole/aiosmtplib#187]
This code is running (**smtplib**):

`import smtplib
from email.mime.text import MIMEText
from settings import host, user, password, sender, receiver, From, To

msg = MIMEText('This is test mail')
msg['Subject'] = 'Test mail'
msg['From'] = From
msg['To'] = To

def send_mail():
    with smtplib.SMTP(host, 587) as server:
        server.login(user, password)
        server.sendmail(sender, receiver, msg.as_string())
        print("mail successfully sent")

send_mail()
`
-----------------------------------------------------------

This code is gives error **(aiosmtplib)**: **"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for"**
`
import asyncio
import aiosmtplib
from email.mime.text import MIMEText
from settings import host, user, password, sender, receiver, From, To

msg = MIMEText('This is test mail')
msg['Subject'] = 'Test mail'
msg['From'] = From
msg['To'] = To

async def send_mail():
    async with aiosmtplib.SMTP(host, 587) as server:
        await server.login(user, password)
        await server.sendmail(sender, receiver, msg.as_string())
        print("mail successfully sent")

event_loop = asyncio.get_event_loop()
event_loop.run_until_complete(send_mail())
`

I couldn't get past the error.
`
        #await server.starttls()
        #await server.login(user, password)
        #await server.sendmail(sender, receiver, msg.as_string())`

I tried many things, it didn't work....

**Comment by cole** [comment]
It looks like the server certificate is not valid. As of version 2.0 aiosmtplib will try to initiate starttls on connect by default, which is a difference from `smtplib`. Try passing `start_tls=False` on init.
