### ISSUE TITLE
packaging issue: deployment of tests

### ISSUE THREAD

**Issue by noraj** [cole/aiosmtplib#195]
The issue is that the pyproject.toml is deploying the tests folder under the root python path and not under this package one.

https://github.com/cole/aiosmtplib/blob/78bf9a8c52245a65d63b08c72d6e4d874d7916bd/pyproject.toml#L13

So it's end up under `/usr/lib/python3.10/site-packages/tests` rather than `/usr/lib/python3.10/site-packages/[aiosmtplib](https://github.com/cole/aiosmtplib/tests` and so conflicts with other packages having the same issue.

Anyway usually test are not shipped in a release package so the easiest would just to remove them. Else they should be deployed in the children directory. 

It's explained in ArchLinux packaging guidelines for Python: https://wiki.archlinux.org/title/Python_package_guidelines#Test_directory_in_site-package

**Comment by cole** [comment]
Thanks for reporting! Should be fixed in 2.0.1 🤞🏻
