### ISSUE TITLE
Gives AttributeError when calling with when

### ISSUE THREAD

**Issue by subodhk01** [cole/aiosmtplib#209]
**Describe the bug**
`SMPT` class gives `AttributeError: __enter__` when used with `with`

**To Reproduce**
```
with SMTP() as smtp:
    smtp.helo()
```

**Expected behaviour**
No exception should be raised

**Comment by subodhk01** [comment]
Is it because I am not using `async with`?

**Comment by cole** [comment]
Yeah, there's no handling for regular `with`, just `async with`.
