### ISSUE TITLE
Package license file

### ISSUE THREAD

**Issue by jakirkham** [cole/aiosmtplib#33]
Could you please add the license file to `MANIFEST.in` and `setup.cfg` so that it will be included in `sdist`s, `whl`s, and other packages?

**Comment by cole** [comment]
Sure, added & will be included in next release.

**Comment by jakirkham** [comment]
Thanks.

**Comment by jakirkham** [comment]
FWIW there is also [this option for wheels]( https://wheel.readthedocs.io/en/stable/#including-the-license-in-the-generated-wheel-file ).
