### ISSUE TITLE
Am I using auth correctly?

### ISSUE THREAD

**Issue by jamesstidard** [cole/aiosmtplib#34]
I'm trying to use a remote SMTP server that requires a email and password. Though the SMTP class doesn't appear to take a username and password as it arguments. I did find the `SMTP.auth_login` function in the documentation.

I've managed to establish what I think is a secure connection, though I'm unsure if I'm using the API correctly. Here's what I have:

```python
smtp = aiosmtplib.SMTP(
    hostname=SMTP_HOSTNAME,
    port=SMTP_PORT,
    use_tls=False)
_ = await smtp.connect()
_ = await smtp.ehlo()
_ = await smtp.starttls()
_ = await smtp.ehlo()
_ = await smtp.auth_login(SMTP_USERNAME, SMTP_PASSWORD)
```
I feel like I may be calling internal API stuff or, if I'm meant to, I may be doing it incorrectly. My knowleage of SMTP servers/protocols is between zero and none.

Thanks for the library.

**Comment by cole** [comment]
Thanks for opening an issue. The API is a bit low level still for STARTTLS with auth connections, I realize it's unnecessarily complicated.  Originally I was trying to follow the `smtplib` API, which uses the same method names. Issue #21 is intended to cover reducing adding these options to init/connect. 

The `login` method is what you should be using (it will try three different authentication schemes if the server supports them, including `auth_login`). It _really_ should documented in the overview; thanks for pointing that out.

Also EHLO is sent automatically if required, so your connection setup can be simplified to
```
smtp = aiosmtplib.SMTP(hostname=SMTP_HOSTNAME, port=SMTP_PORT, use_tls=False)
await smtp.connect()
await smtp.starttls()
await smtp.login(SMTP_USERNAME, SMTP_PASSWORD)
```

**Comment by jamesstidard** [comment]
@cole That's great thank you. I some how missed the `login` method.

Having the username and password in the init call will be a nice addition.

Thanks again for the library.
