### ISSUE TITLE
Reconnecting after a failed connect seems to hang indefinitely

### ISSUE THREAD

**Issue by lufte** [cole/aiosmtplib#38]
Try the following snippet:
```python
import aiosmtplib, asyncio

async def c():
    s = aiosmtplib.SMTP('asd.asd.com')
    try:
        await s.connect()
    except:
        print('error raised for the first time')
        try:
            await s.connect()
        except:
            print('error raised for the first time, exiting')
            return

asyncio.get_event_loop().run_until_complete(c())
```
I would expect for the same error to be raised twice, but the obtained result was that an error is raised only for the first connection and the second one hangs indefinitely.

I'm running aiosmtplib 1.0.2 under python 3.6.6.

**Comment by cole** [comment]
Confirmed, I see the same thing. This is odd behavior.

**Comment by cole** [comment]
On investigation, it seems that we aren't cleaning up properly on connection failure. If you call `s.close()` in the first except block, before trying to connect again, it should work. I'll write up a test for it and put a fix into master.

**Comment by lufte** [comment]
Oh that makes sense. Awesome, thanks!
