### ISSUE TITLE
Upload new release to PyPI

### ISSUE THREAD

**Issue by montag451** [cole/aiosmtplib#44]
Following the resolution of #42, is it possible to upload a new release to PyPI? I'm asking this because at my work place we rely on PyPI to deploy our softwares.

PS : I'm sorry to use the issue tracker to ask you that but I don't know a better way :(

**Comment by cole** [comment]
Hi, I'll try to get a release out later this week. In the meantime, you can have pip pull the package from git if that helps.

**Comment by montag451** [comment]
OK, thank you!

**Comment by cole** [comment]
1.0.5 released.

**Comment by montag451** [comment]
Very nice, thank you! Keep up the good work :wink:
