### ISSUE TITLE
aiohttp

### ISSUE THREAD

**Issue by kodkuce** [cole/aiosmtplib#45]
How to implement this with aiohttp server, example for postgres asyncpg i can create a pool but here duno how at all :(

**Comment by cole** [comment]
aiosmtplib doesn't have connection pooling (yet, this is something under consideration for future). You can just create a connection in the aiohttp handler, if that's where you want to send an email. Or you can track the `SMTP` instance in the `app` (e.g. set `app['smtp'] = aiosmtplib.SMTP(...)`), but that is a bit more complicated as you'll have to retry the connection on disconnect, etc, so I'd start with the first approach.
