### ISSUE TITLE
Default connect timeout doesn't work

### ISSUE THREAD

**Issue by Lenka42** [cole/aiosmtplib#50]
I have a problem with connect operation not terminating after timeout. For example you can try to connect to wrong port:
```
import asyncio
import aiosmtplib
loop = asyncio.get_event_loop()
smtp = aiosmtplib.SMTP('smtp-mail.outlook.com', 5871, use_tls=True)
async def connect_and_print(smtp):
    await smtp.connect()
    print('connected')
loop.run_until_complete(connect_and_print(smtp))
```
This code hangs for a long-long time. I also tried to wrap connect into `asyncio.wait_for` but it also doesn't work.

**Comment by cole** [comment]
There is a bug (no open issue for it, but it's already been fixed in the dev branch) in 1.0.5 where the docs specify the default timeout as 60 seconds but it's actually None (so unlimited). Sorry about that. You can specify a timeout manually though:

```
import asyncio
import aiosmtplib
loop = asyncio.get_event_loop()
smtp = aiosmtplib.SMTP('smtp-mail.outlook.com', 5871, use_tls=True, timeout=10.0)
async def connect_and_print(smtp):
    await smtp.connect()
    print('connected')
loop.run_until_complete(connect_and_print(smtp))
```

**Comment by decaz** [comment]
@cole is it known when next release which includes this fix will be available?

**Comment by cole** [comment]
@decaz not yet. I'd recommend you specify a timeout manually (60 will be the future default).

**Comment by cole** [comment]
The default is now 60 seconds in 1.0.6.
