### ISSUE TITLE
InvalidStateError

### ISSUE THREAD

**Issue by decaz** [cole/aiosmtplib#53]
I'm using the last revision (`f5ce158`) of the `master` branch and getting the following exception:
```
InvalidStateError: invalid state
  File "asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "asyncio/selector_events.py", line 913, in _call_connection_lost
    super()._call_connection_lost(exc)
  File "asyncio/selector_events.py", line 687, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "aiosmtplib/protocol.py", line 79, in connection_lost
    self._connection_lost_waiter.set_result(None)
```

**Comment by decaz** [comment]
And another one:
```
InvalidStateError: invalid state
  File "asyncio/selector_events.py", line 813, in _read_ready__data_received
    self._protocol.data_received(data)
  File "aiosmtplib/protocol.py", line 107, in data_received
    self._response_waiter.set_result(response)
```

**Comment by cole** [comment]
Thanks for filing. Is this consistently reproducible? Any change you could provide a sample that triggers it?

**Comment by decaz** [comment]
Yes, the first case is very common but the second is rare. I'm just using `await aiosmtplib.send(...)` and nothing more.

Didn't dig in the `aiosmtplib` code but maybe `<future>.done()` checks are missing where `<future>.set_result(...)` or `<future>.set_exception(...)` is called?

**Comment by cole** [comment]
That was it, exactly. Can you try again with 8f7a0117?

**Comment by decaz** [comment]
Just updated to the last revision, - no errors yet visible.

**Comment by decaz** [comment]
Unfortunately just got the second case:
```
InvalidStateError: invalid state
  File "asyncio/selector_events.py", line 813, in _read_ready__data_received
    self._protocol.data_received(data)
  File "aiosmtplib/protocol.py", line 102, in data_received
    self._response_waiter.set_result(response)
```

**Comment by cole** [comment]
Huh, I still don't really understand why `data_received` is getting multiple complete responses without the waiter being awaited in between. We can just put in a check for `done` but I think there might be a larger problem here.

Can you try with db7ab6? It won't fix the issue, but it adds a clearer exception.

**Comment by decaz** [comment]
@cole just got it three times in a row:
```
RuntimeError: data_received called with an unexpected response waiter state: <Future finished result=(250, 2.1.5 Ok)> (data: b'221 2.0.0 Bye\r\n')
  File "asyncio/selector_events.py", line 813, in _read_ready__data_received
    self._protocol.data_received(data)
  File "aiosmtplib/protocol.py", line 94, in data_received
    "{!r} (data: {})".format(self._response_waiter, data)
```

**Comment by cole** [comment]
Huh, ok, it looks like I've just an unprompted server disconnect (timeout maybe)? I've put a check in for `_response_waiter.done()` so you shouldn't see the error anymore.
 
Thanks for helping debug this.

**Comment by decaz** [comment]
Another case of this exception with new text:
```
RuntimeError: data_received called with an unexpected response waiter state: <Future cancelled> (data: b'220 my.host.ru ESMTP MTA\r\n')
  File "asyncio/selector_events.py", line 813, in _read_ready__data_received
    self._protocol.data_received(data)
  File "aiosmtplib/protocol.py", line 94, in data_received
    "{!r} (data: {})".format(self._response_waiter, data)
```

**Comment by cole** [comment]
That is more confusing — that future is only cancelled in `connection_lost`, and `data_received` should not be called after `connection_lost`. I'll investigate further.

**Comment by cole** [comment]
Just to confirm, are you stopping/starting the event loop or anything?

I don't understand why it is happening, but it looks like in the remaining error case, the connection is already closing as we get a EHLO response — in that case we can just discard the message.

**Comment by decaz** [comment]
@cole nope, nothing unusual with event loop.

But sometimes I'm getting the following timeout exception from server:
```
SMTPReadTimeoutError
Timed out waiting for server response
```
Maybe this could lead to `SMTPProtocol.connection_lost` was called at the client side while `SMTPProtocol.data_received` was suddenly called.

But the case with `RuntimeError` (cancelled future) was just once.

**Comment by decaz** [comment]
I think we can close it for now because there are no any new exceptions raised at this moment. @cole thanks!
